### ISSUE TITLE
gigi się nie ładują po klinięciu, nie da się cofnąć

### ISSUE THREAD

**Issue by mg-pomorska** [gig3r-com/giger#106]
LOGIN: matsumura
HASŁO: drone

"Telefon (xiaomi mi 9 lite), android, chrome, na kompie na chrome to samo, w załączniku ekran /1112 to pierwszy gig niebieski, który kliknąłem, oraz po kliknięciu wstecz w przeglądarce"
![e68647e4-443f-4f4e-a36f-9d5a8d3fa07b](https://github.com/gig3r-com/giger/assets/169362989/8b4ad9ac-9542-434d-b23a-86931853dd7e)
![b7c14855-b930-4246-b5d4-49573d85e5d1](https://github.com/gig3r-com/giger/assets/169362989/95a2c63d-2cb9-4c50-b516-c48b9ad3999d)

**Comment by EvilProfesseur** [comment]
naprawione na dev
