### ISSUE TITLE
nie widać wszystkich pól w myID, to może być scrollowanie też

### ISSUE THREAD

**Issue by mg-pomorska** [gig3r-com/giger#109]
Kasia Czpak - bug aplikacji, na iphonie nie mogę zobaczyć dwóch najniższych zakładek w myID, zasłania stopka, wysyłam screena w załączniku.
![image_6487327](https://github.com/gig3r-com/giger/assets/169362989/09fa9b4a-5a42-4d3a-89d5-7653c0c46c9c)

**Comment by EvilProfesseur** [comment]
done
