### ISSUE TITLE
Kliknięcie w strzałkę pokazuje podgląd na samym dole listy

### ISSUE THREAD

**Issue by zefir6** [gig3r-com/giger#147]
Kliknięcie w strzałkę pokazuje podgląd na samym dole listy, ja myślałem że tego podglądu nie ma, gracze na to marudzą. Ale no - nie jest to priorytet.

**Comment by toperz** [comment]
Po kliknięciu na strzałkę, formularz ze szczegółami kontaktu pojawia się pod całą lista kontaktów.

**Comment by EvilProfesseur** [comment]
done
