### ISSUE TITLE
znikające #highsecurity

### ISSUE THREAD

**Issue by mg-pomorska** [gig3r-com/giger#151]
Sprawdziłem jeszcze raz. Po wejściu w apkę widnieje High security: Yes, ale po odświeżeniu i ponownym wejściu w [my.id](http://my.id/) zmienia się na High security: No. Samsung S23. Android. Załączam nagranie.

Po zamknięciu i ponownym otworzeniu aplikacji znowu jest High security: Yes.

Uploading Screen_Recording_20240523_111312_Chrome.mp4…

**Comment by EvilProfesseur** [comment]
@ZielnikJ user/private i user/simple zwracaja różne wartosci. przepiałem wszystko na simple takze nie bedzie nam to teraz przeszkadzac
