### ISSUE TITLE
nie ładują się gigi - jest loading; konto dog_00

### ISSUE THREAD

**Issue by mg-pomorska** [gig3r-com/giger#152]
Co prawda konto bankowe, chat i dodatkowe info w more info zainstalowało się, ale niestety muszę zgłosić, że na karcie gigów mam wyłącznie ciągle komunikat "loading", nawet po kilku godzinach.  Reinstalowałam apkę 2 razy.

**Comment by EvilProfesseur** [comment]
scenario dodalo nieuzgodnioną kategorię, dane zmienione
